# Generated by Django 4.2.3 on 2023-08-30 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_productreview_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='c_id',
            new_name='category',
        ),
    ]
