# Generated by Django 4.2.3 on 2023-09-06 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_c_id_subcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='date_created',
        ),
    ]
