# Generated by Django 4.2.3 on 2023-08-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_address_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='mobile',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
