# Generated by Django 4.2.3 on 2023-09-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('inprocess', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='inprocess', max_length=30),
        ),
    ]
